name: publish
on:
  push:
    tags:
      - '*'

jobs:
  build:
    uses: ./.github/workflows/build.yml

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: packages
          path: packages
      - uses: actions/download-artifact@v3
        with:
          name: benchmark
          path: benchmark/build
      - run: cp README.md packages/spectypes
      - run: cp README.md packages/babel-plugin-spectypes
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
      - run: sudo npm i -g pnpm@6.24.2
      - run: pnpm i -r --frozen-lockfile
      - name: setup git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: benchmark
        run: |
          pnpm report -r
          git commit -am "benchmark report [skip ci]"
          git push origin HEAD:main
      - run: pnpm -r publish --access public --no-git-checks
