name: publish
on:
  push:
    tags:
      - '*'

jobs:
  build:
    uses: ./.github/workflows/build.yml

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: packages
          path: packages
      - uses: actions/download-artifact@v3
        with:
          name: benchmark
          path: benchmark/build
      - run: ls -R
      - run: cp README.md packages/spectypes
      - run: cp README.md packages/babel-plugin-spectypes
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
      - run: sudo npm i -g pnpm@6.24.2
      - run: pnpm i --frozen-lockfile
      - name: setup git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Get Branch
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw/origin\/}
          echo ::set-env name=BRANCH::$branch
      - run: echo ${{ env.BRANCH }}
      - name: benchmark
        run: |
          cd benchmark
          pnpm report
          git commit -am "benchmark report [skip ci]"
          git push
      - run: pnpm -r publish --access public --no-git-checks
